on:
  workflow_dispatch:
  pull_request:
    types:
      - synchronize
  schedule:
    - cron: '0 */1 * * *' # Runs every 1 hour

  check_bake_time:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove the bake-time label and unblock mergeable_state
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const delayHours = 24;
            const millisInAnHour = 60 * 60 * 1000;
            const delayMilliseconds = delayHours * millisInAnHour;

            // List all pull requests with the delayed-merge label
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'bake-time'
            });

            const now = new Date();
            for (const pr of pullRequests) {
              const updatedAt = new Date(pr.updated_at);

              // Check if the pull request has not been updated in the specified delay
              if (now - updatedAt >= delayMilliseconds) {
                console.log(`Marking status check as successful for PR #${pr.number}`);

                // Remove the label
                await github.rest.issues.removeLabel({
                  issue_number: pr.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: 'bake-time'
                });

                // Mark the status check as successful
                await github.rest.repos.createCommitStatus({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  sha: pr.head.sha,
                  state: 'success',
                  context: 'Bake time delay',
                  description: 'The bake time delay has passed. This PR can be merged.'
                });
              } else {
                const timeRemaining = (delayMilliseconds - (now - updatedAt)) / (millisInAnHour);
                console.log(`PR #${pr.number} still needs to wait for ${timeRemaining.toFixed(2)} hours before the delay is over.`);
              }
            }
