name: Bake time

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add_bake_time_delay:
    name: "Add Bake Time Delay"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bake-time']
            });

            const { data: checkCreation } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Baking...',
              head_sha: context.payload.pull_request.head.sha,
              status: 'in_progress',
              output: {
                title: 'Waiting for the delay to pass before merging',
                summary: 'This check will pass once the delay is over'
              }
            });
            console.log(`Created check run, details: ${JSON.stringify(checkCreation, undefined, 3)}`);
