name: Finish Bake Time

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # Runs every 1 hour 

jobs:
  finish_bake_time:
    name: "Finish baking pull requests"
    runs-on: ubuntu-latest
    steps:
      - uses: peternied/bake-time/finish-baking@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delay-hours: 0
