name: Bake time

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  require_bake_time:
    runs-on: ubuntu-latest
    steps:
      - name: Add a bake time delay before merge is allowed
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: result1 } = await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bake-time']
            });

            console.log(`Add label result, ${JSON.stringify(result1), undefined, 3}`);

            const { data: result2 } = await github.rest.checks.createSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
            });
            console.log(`Add create suite result, ${JSON.stringify(result2), undefined, 3}`);

            const { data: result3 } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Bake Time Delayed Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'action_required',
              output: {
                title: 'Waiting for the delay to pass before merging',
                summary: 'This check will pass once the delay is over'
              }
            });
            console.log(`Add create run result, ${JSON.stringify(result3), undefined, 3}`);
